<a href="https://colab.research.google.com/github/dpkasahu/Python_library/blob/main/gfgnumpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. it is faster than python lists and optimized for handling large datasets.
#numpy.array() it is for basic array creation
#numpy.arrange()


List vs numpy array

In [5]:
py_list=[1,2,3]
print(py_list * 2)

[1, 2, 3, 1, 2, 3]


In [6]:
import numpy as np
np_array=np.array([1,2,3]) #element wise multiplication
print(np_array * 2)

[2 4 6]


In [10]:
import time
start = time.time()
py_list=[i*2  for i in range(10000000)]
print("list:", time.time()-start)
start=time.time()
np_array=np.array([i*2 for i in range(10000000)])
print("numpy array:",time.time()-start)

list: 0.7773799896240234
numpy array: 1.3663201332092285


Creating array from scratch

In [11]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
full = np.full((2,3),5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
random=np.random.random((2,3))
random

array([[0.63688008, 0.47537193, 0.24572483],
       [0.67783874, 0.06354924, 0.47217658]])

In [15]:
sequence = np.arange(10,20,2)
sequence

array([10, 12, 14, 16, 18])

vector,matrix and tensor

In [17]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [ ]:
matrix = np.array([1,2,3],[4,5,6])
matrix

In [19]:
tensor = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Array properties

In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape) #shape of array
print(arr.ndim) #dimension of an array
print(arr.dtype) #datatype of an array
print(arr.size)  #size of an array

(2, 3)
2
int64
6


Array reshaping

In [29]:
arr=np.arange(12)
print("original array:" , arr)
arr1 = arr.reshape((3,4))
print("Reshaped array :", arr1)
arr2=arr1.flatten()
print("Flattened array :",arr2)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array : [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
raveled= arr1.ravel()
raveled #returns view instead of copy
#transpose
transpose = arr1.T
transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])