<a href="https://colab.research.google.com/github/dpkasahu/numpy/blob/main/Gfgnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NumPy stands for Numerical Python and is used for handling large, multi-dimensional arrays and matrices. Unlike Python's built-in lists NumPy arrays provide efficient storage and faster processing for numerical and scientific computations.
#Types of Array
import numpy as np
a=[1,2,3,4]
arr=np.array(a)
arr

array([1, 2, 3, 4])

Multidimensional Array

In [3]:
import numpy as np
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
arr = np.array([list_1,
                         list_2,
                         list_3])
# arr
arr.shape

(3, 4)

In [4]:
import numpy as np
arr=np.array([[0,4,2]])
arr.dtype

dtype('int64')

Different Ways of Creating Numpy Array

In [5]:
import numpy as np
arr = np.array([3,4,5,5])
print("Array :",arr)

Array : [3 4 5 5]


numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.

In [ ]:
import numpy as np
var = "Deepika"
arr = np.fromiter(var, dtype = 'U2')
print("fromiter() array :",
      arr)

 numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.
numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.

Syntax:  numpy.arange( start , stop, step , dtype=None )


In [6]:
import numpy as np

np.arange(1, 20 , 2,
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.

Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [7]:
import numpy as np

np.linspace(3.5, 10, 3,
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

 numpy.empty(): This function create a new array of given shape and type without initializing value.

Syntax: numpy.empty(shape, dtype=float, order='C')

In [8]:
import numpy as np

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[ 543210425,   11707264, -377919840],
       [         0,          0,      32598],
       [         0, -705164816, -305600784],
       [         0,      32598,      32598]], dtype=int32)

numpy.ones(): This function is used to get a new array of given shape and type filled with ones (1).
Syntax: numpy.ones(shape, dtype=None, order='C')

In [ ]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

numpy.zeros(): This function is used to get a new array of given shape and type filled with zeros (0).

Syntax: numpy.ones(shape, dtype=None)

In [9]:
import numpy as np
np.zeros([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

1. Addition of Arrays

In [10]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
add_ans = np.add(a, b)
print(add_ans)

[  7  77  23 130]


 Subtraction of Arrays

In [ ]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
sub_ans = np.subtract(a, b)
print(sub_ans)

Multiplication of Arrays

In [11]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]


Division of Arrays

In [12]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


Exponentiation (Power)

In [13]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
pow_ans = np.power(a, b)
print(pow_ans)

[                 25          1934917632        137858491849
 1152921504606846976]


 Modulus Operation

In [ ]:
import numpy as np
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
mod_ans = np.mod(a, b)
print(mod_ans)